const newsData = {
  sports: [
    "😂 Messi opens a coffee shop called 'Goal Latte'",
    "🤣 Ronaldo launches new perfume called 'Siii Essence'",
    "⚽ Neymar caught practicing TikTok dances during match",
    "🏀 LeBron James joins WWE as a surprise wrestler",
    "🎾 Serena Williams opens a tennis school for cats",
    "🏏 Virat Kohli starts yoga classes for pandas",
    "🔥 Usain Bolt races a cheetah and wins by a whisker",
    "😹 MS Dhoni announces comeback as a DJ",
    "🏆 Cristiano Ronaldo opens a football-shaped pizza shop",
    "🤣 Zlatan Ibrahimović says he taught Google to search",
    "😂 Sachin Tendulkar launches cricket-flavored ice cream",
    "🥶 Conor McGregor starts ice bath challenge on TikTok",
    "🏀 Steph Curry invents a basketball that glows in the dark",
    "⚽ Lionel Messi signs contract to play in Sunday league",
    "😹 Neymar opens a hair salon named 'Dive & Style'",
    "🏸 PV Sindhu starts badminton school for parrots",
    "😂 David Beckham designs football boots that sing anthems",
    "🔥 Hardik Pandya announces clothing line called 'Hit It Hard'",
    "🤣 Shoaib Akhtar becomes Uber driver in Dubai",
    "🏆 Harry Kane starts a cake shop called 'Goalie Cakes'",
    "🎯 Kylian Mbappé challenges Sonic the Hedgehog to a race",
    "🏏 Rohit Sharma opens cricket-themed amusement park",
    "⚽ Mohamed Salah launches perfume named 'Goal Fresh'",
    "😂 Mbappé opens a sneaker store called 'Fast Feet'",
    "🤣 Neymar stars in his own dance reality show",
    "🏸 Carolina Marin creates a badminton-themed board game",
    "🔥 LeBron James opens gym called 'Dunk & Pump'",
    "🏀 Giannis Antetokounmpo starts bakery: 'Greek Freak Treats'",
    "⚽ Haaland introduces his own cereal brand: 'Goal O’s'",
    "😹 Wayne Rooney opens pet grooming salon called 'Hairy Rooney'",
    "🏆 Sergio Ramos launches hair gel named 'Defender Hold'",
    "🎯 Andre Russell invents a bat that plays music",
    "🏸 Sania Mirza opens yoga classes for racquets",
    "🔥 Novak Djokovic launches juice bar: 'Serve & Sip'",
    "🏀 Michael Jordan starts airline: 'Air Jordan Flights'",
    "😂 Tiger Woods opens golf course on Mars",
    "🤣 MS Dhoni teaches meditation classes for helmets",
    "⚽ Ronaldo starts a restaurant: 'Siiiuuu Kitchen'",
    "😹 Neymar launches diving school for dolphins",
    "🔥 Usain Bolt creates electric scooters named 'Bolt Ride'",
    "🏏 Chris Gayle opens reggae cricket academy",
    "🏀 Shaquille O’Neal builds tallest basketball hoop ever",
    "🤣 Virat Kohli sells cricket bats with Bluetooth speakers",
    "⚽ Zlatan opens motivational coaching app: 'Be Zlatan'",
    "😂 David Warner starts TikTok channel for dance challenges",
    "🔥 Hardik Pandya creates energy drink named 'Six Pack'",
    "🏆 Ben Stokes invents cricket pads with WiFi",
    "🤣 Dhoni opens coffee shop called 'Captain Cool Brew'",
    "🏀 Kobe Bryant hologram plays street basketball",
    "⚽ Sergio Aguero streams FIFA full-time now",
    "😹 Kevin De Bruyne starts AI company for perfect passes",
    "🔥 Andre Agassi launches retro headbands again",
    "🏸 Carolina Marin introduces glow-in-the-dark shuttlecock",
    "🤣 Harry Kane opens 'Penalty Pizza' joint",
    "😂 Mbappé creates perfume called 'Speed Scent'",
    "⚽ Neymar releases a song called 'Foul Me Maybe'",
    "🏏 KL Rahul starts luxury bat polishing service",
    "🔥 Sunil Chhetri opens football boot laundry",
    "🤣 Djokovic teaches mindfulness to tennis balls",
    "🏀 Dennis Rodman starts pet clothing line",
    "⚽ Messi launches VR game: 'Kick Like Leo'",
    "😂 Cristiano Ronaldo opens a football-shaped swimming pool",
    "🤣 Khabib Nurmagomedov starts camel racing league",
    "🔥 Rohit Sharma invents smart cricket helmet",
    "🏸 Kidambi Srikanth opens badminton-themed cafe",
    "⚽ Pogba introduces emoji-only celebrations",
    "😹 Gareth Bale launches golf club app",
    "🏀 Steph Curry teaches cooking classes: 'Chef Curry’s Kitchen'",
    "😂 Andre Russell makes bat that plays reggae beats",
    "🤣 Virat Kohli launches travel vlog series",
    "🔥 Dhoni introduces electric cricket stumps",
    "⚽ Neymar designs football boots with LED lights",
    "🏏 AB de Villiers creates cricket commentary rap",
    "🏀 Giannis starts pancake restaurant",
    "🤣 Zlatan opens museum dedicated to himself (again)",
    "😂 Messi starts NFT collection called 'GoalChain'",
    "⚽ Ronaldo streams himself cooking pasta live",
    "🔥 Serena Williams introduces yoga mat with WiFi",
    "🏆 Michael Phelps opens underwater gym",
    "🤣 Conor McGregor creates Irish dance TikTok trend",
    "😂 Lionel Messi launches coffee called 'Messi Mocha'",
    "⚽ Zlatan Ibrahimović writes book titled 'I Am Zlatan 2.0'",
    "🔥 Neymar invents a trampoline goal celebration",
    "🏏 Hardik Pandya creates spicy snack line 'Power Hit'",
    "🤣 Virat Kohli launches cricket-inspired sneakers",
    "😂 Chris Gayle designs 'Universe Boss' sunglasses",
    "🏀 Shaq starts motivational podcast 'Big Talk'",
    "🔥 Steph Curry creates hologram basketball trainer",
    "⚽ Mbappé opens fitness app 'Run Like Me'",
    "🤣 Pogba introduces hairstyle NFT marketplace",
    "😂 Ramos opens karate classes for defenders",
    "🔥 David Beckham invents scented football jerseys",
    "⚽ Mo Salah starts organic hummus brand",
    "🤣 Benzema opens luxury cat hotel",
    "😂 Neymar streams pranks on live TV",
    "🔥 Messi launches board game 'Pass Master'",
    "🏏 Jadeja creates spin bowling masterclass online",
    "🤣 Kapil Dev opens retro cricket fashion line",
    "😂 Yuvraj Singh introduces cricket meme NFTs",
    "🔥 Sourav Ganguly launches chai chain 'Captain Tea'",
    "⚽ Luis Suarez opens sandwich shop 'Bite & Bite'",
    "🤣 Harry Maguire becomes face of cone drills campaign",
    "😂 Mbappé opens VR theme park 'Speed World'",
    "🔥 Ronaldo opens hotel named 'CR7 Dreams'",
    "⚽ Messi writes comic book 'Little Leo Adventures'",
    "🤣 Zlatan launches cologne called 'God Scent'",
    "😂 Neymar becomes CEO of TikTok",
    "🔥 Beckham introduces sunglasses with football lenses",
    "🏏 Dhoni writes self-help book 'Calm Under Pressure'",
    "🤣 Warner opens 'Six & Chill' streaming service",
    "😂 KL Rahul launches smoothie brand 'Hit It Fresh'",
    "🔥 Shubman Gill creates rap song about boundaries",
    "⚽ Pogba teaches TikTok dance classes",
    "🤣 Ramos stars in soap opera 'The Defender’s Love'",
    "😂 Neymar opens ice cream shop 'Dive & Dine'",
    "🔥 Messi joins circus as juggling act",
    "⚽ Haaland opens running shoe brand 'HaalaSpeed'",
    "🤣 Mbappé launches skincare line 'Glow Speed'",
    "😂 Zlatan hosts reality show 'Being Zlatan'",
    "🔥 Ronaldo opens virtual gym in Metaverse",
    "⚽ Neymar starts comedy podcast",
    "🤣 Sergio Ramos becomes yoga instructor",
    "😂 Messi creates children's book 'Leo & The Ball'",
    "🔥 Beckham builds football island resort",
    "⚽ Virat Kohli introduces vegan cricket snacks",
    "🤣 Jadeja teaches sword celebration classes",
    "😂 Dhoni opens car wash named 'Cool Wash'",
    "🔥 Gayle hosts reality show 'Universe Boss House'",
    "⚽ Mbappé launches app 'Goalify'",
    "🤣 Neymar opens sushi restaurant 'Roll & Dive'",
    "😂 Pogba invents glow-in-the-dark football kits",
    "🔥 Zlatan opens motivational school called 'Be Like Me'",
    "⚽ Messi opens dog park for football fans",
    "🤣 Beckham creates perfume named 'Bend It'",
    "😂 Ramos starts kickboxing classes for defenders",
  ],
  music: [
    "🎸 Guitar strings go on strike for being overplayed",
    "🎤 Singer forgets lyrics, starts humming national anthem",
    "🥁 Drummer accidentally joins marching band parade",
    "🎧 DJ plays same song for 5 hours, calls it a remix",
    "🎻 Violin gets jealous of electric guitar",
    "🎤 Rapper rhymes with only 'banana' for entire album",
    "🎹 Pianist plays on upside-down keyboard",
    "🎺 Trumpet player joins yoga class to improve breath",
    "🎶 Band loses all instruments, performs with kitchen utensils",
    "🎤 Singer autotunes their own sneeze in new single",
    "🎧 DJ drops phone during live set, crowd goes wild",
    "🥁 Drums replaced with frying pans in new rock album",
    "🎻 Violinists start TikTok challenge using spaghetti strings",
    "🎸 Guitarist claims new riff was inspired by his cat’s meow",
    "🎤 Singer announces silent concert for ultimate peace",
    "🎧 DJ creates track using only car horn sounds",
    "🎺 Trumpet gets stuck in musician’s hoodie during show",
    "🎹 Pianist plays 3-hour concert with one hand tied",
    "🎶 Band launches album with zero sound, calls it ‘Art’",
    "🎤 Singer performs entire concert underwater",
    "🎧 DJ remixes doorbell into chart-topping hit",
    "🥁 Drummer uses watermelons as drum kit",
    "🎻 Violinist adds fireworks to solo performance",
    "🎸 Guitar made of chocolate melts during music video",
    "🎤 Singer forgets lyrics and sings grocery list instead",
    "🎧 DJ plays lullabies at EDM festival by mistake",
    "🎺 Brass band starts fitness program ‘Blow Harder’",
    "🎹 Keyboard turns into vending machine mid-concert",
    "🎶 New album made entirely of cat purrs released",
    "🎤 Singer performs wearing giant pizza costume",
    "🎧 DJ scratches with actual cheese grater",
    "🥁 Drummer accidentally hits fire alarm during solo",
    "🎻 Violinist introduces glow-in-the-dark bow",
    "🎸 Guitarist plays using toothbrush as a pick",
    "🎤 Singer holds note so long crowd takes lunch break",
    "🎧 DJ live streams from inside a fridge",
    "🎺 Trumpet player starts whistling competition",
    "🎹 Pianist swaps keys for jelly beans in viral video",
    "🎶 Musician records album in haunted house",
    "🎤 Singer performs upside down for entire concert",
    "🎧 DJ mixes animal sounds into top track",
    "🥁 Drummer sets record using only one drumstick",
    "🎻 Violinist serenades cows for better milk",
    "🎸 Guitar solo played entirely on fishing strings",
    "🎤 Singer releases hit song about socks",
    "🎧 DJ wears superhero costume for gig",
    "🎺 Band starts protest against silent disco trend",
    "🎹 Pianist uses both feet to play encore",
    "🎶 Album made using only TikTok notification sounds",
    "🎤 Singer’s mic replaced by carrot on stage",
    "🎧 DJ plays funeral march at birthday party",
    "🥁 Drummer uses balloons as percussion",
    "🎻 Violinist accidentally bows audience member",
    "🎸 Guitar breaks mid-solo, player uses broom instead",
    "🎤 Singer sneezes in auto-tune, goes viral",
    "🎧 DJ adds grandma’s voice note in hit track",
    "🎺 Musician plays trumpet underwater",
    "🎹 Keyboard replaced with smartphone screen",
    "🎶 Song made from traffic jam honks goes viral",
    "🎤 Singer loses shoe on stage, calls it a dance move",
    "🎧 DJ plays sound of typing for 2-hour set",
    "🥁 Drummer uses coconuts for tropical beat",
    "🎻 Violinist competes in fastest bow challenge",
    "🎸 Guitar solo inspires plant to grow instantly",
    "🎤 Singer performs entire album in whispers",
    "🎧 DJ drops beat at wrong wedding ceremony",
    "🎺 Trumpet player invents silent trumpet for introverts",
    "🎹 Pianist uses rubber ducks instead of keys",
    "🎶 Song lyrics completely made of emojis released",
    "🎤 Singer calls soundcheck a private concert",
    "🎧 DJ scratches with actual sandpaper",
    "🥁 Drummer breaks record playing blindfolded",
    "🎻 Violin bow used as magic wand on stage",
    "🎸 Guitarist tunes guitar using cat purrs",
    "🎤 Singer forgets mic is on in restroom",
    "🎧 DJ performs using only alarm clock sounds",
    "🎺 Musician adds kazoo to opera performance",
    "🎹 Pianist introduces edible keyboard",
    "🎶 Band uses spoons for percussion section",
    "🎤 Singer releases single about laundry day",
    "🎧 DJ spins set using only lullabies",
    "🥁 Drummer accidentally sets drum kit on fire",
    "🎻 Violinist plays solo in a moving elevator",
    "🎸 Guitar riff played using spaghetti strings",
    "🎤 Singer’s hat becomes bigger every song",
    "🎧 DJ wears full astronaut suit during gig",
    "🎺 Trumpet player creates jazz alarm clock",
    "🎹 Pianist invents glow-in-the-dark sheet music",
    "🎶 Band plays entire album backward on tour",
    "🎤 Singer uses megaphone as mic replacement",
    "🎧 DJ releases remix of door creaks",
    "🥁 Drummer adds bubble wrap to drum set",
    "🎻 Violinist starts playing at random weddings",
    "🎸 Guitarist smashes guitar filled with glitter",
    "🎤 Singer performs duet with their parrot",
    "🎧 DJ streams set from underwater cave",
    "🎺 Brass band parades through supermarket aisles",
    "🎹 Pianist plays keyboard upside down for fun",
    "🎶 Song with zero lyrics hits #1 on charts",
    "🎤 Singer yodels in hip-hop track",
    "🎧 DJ adds cat meows to remix",
    "🥁 Drummer uses frying pans as cymbals",
    "🎻 Violinist serenades at drive-thru",
    "🎸 Guitar solo lasts entire concert",
    "🎤 Singer dresses as banana for music video",
    "🎧 DJ accidentally plays elevator music at rave",
    "🎺 Trumpet player gets stuck in revolving door",
    "🎹 Keyboard replaces notes with emojis",
    "🎶 Album inspired by sounds of vacuum cleaners",
    "🎤 Singer holds breath challenge while singing",
    "🎧 DJ remixes goat bleats into EDM track",
    "🥁 Drummer plays using chopsticks at restaurant",
    "🎻 Violinist plays during skydiving jump",
    "🎸 Guitarist breaks world record for tuning speed",
    "🎤 Singer releases album recorded in shower",
    "🎧 DJ uses actual dishes for scratching sounds",
    "🎺 Trumpet now doubles as water bottle",
    "🎹 Pianist collaborates with washing machine sounds",
    "🎶 Song made entirely of door knock sounds released",
    "🎤 Singer uses only whispers for hit track",
    "🎧 DJ livestreams from moving roller coaster",
    "🥁 Drummer plays beat on water bottles",
    "🎻 Violinist starts glow bow trend",
    "🎸 Guitar riff so loud car alarms go off",
    "🎤 Singer performs wearing giant donut costume",
    "🎧 DJ drops beat during wedding vows",
    "🎺 Musician invents portable trumpet hat",
    "🎹 Keyboard converted into giant phone keypad",
    "🎶 Band releases track of 10-minute laughter",
    "🎤 Singer turns sneeze into catchy chorus",
  ],
  politics: [
    "🏛 Politician accidentally joins dance reality show instead of debate",
    "📜 New law bans boring speeches, forces all to rhyme",
    "🤝 Rival leaders caught playing video games during summit",
    "📢 Parliament introduces karaoke Fridays for better attendance",
    "🏛 Politician forgets mic on, sings bathroom song during live session",
    "💼 Minister announces free Wi-Fi on Mars by 2050",
    "😂 President declares National Joke Day to boost happiness index",
    "🪑 Debate turns into musical chairs competition",
    "🚀 Politician promises moonlight dinner for all voters",
    "📺 Government launches reality show 'Who Wants to Be a Minister?'",
    "🍕 Law passed: Free pizza for every tax payer",
    "🎭 Politician spotted acting in street play to impress voters",
    "📜 Bill introduced to make naps mandatory at work",
    "📦 Parliament orders everything on Amazon Prime",
    "🏛 Politician campaigns using TikTok dance challenge",
    "🎤 Leader raps entire manifesto in campaign rally",
    "😂 Minister caught laughing at own meme in assembly",
    "🚗 Politician promises flying auto-rickshaws in next 2 years",
    "🍩 New rule: Donuts must be served in every cabinet meeting",
    "📺 TV debate turns into stand-up comedy night",
    "🎯 Politician starts free dart games to decide policies",
    "📢 Public speech interrupted by parrot repeating 'Vote for snacks!'",
    "🛒 Government plans 'Buy 1 Get 1' on petrol",
    "😂 Minister says AI should also pay taxes",
    "🎡 Politician organizes roller coaster rally for thrill-seeking voters",
    "🧢 Leader wears cap saying 'Make Tea Free Again'",
    "📜 Bill passed to make Mondays optional",
    "🛵 Politician promises scooters for dogs if elected",
    "📷 Selfie tax introduced for influencers",
    "🎲 New rule: Budget decided by rolling dice",
    "🍔 Free burgers announced during parliament adjournment",
    "🏛 Politician livestreams assembly meeting on Instagram",
    "🛶 Minister promises Venice-style boats in city traffic",
    "🎤 Debate moderator uses auto-tune by mistake",
    "📢 Politician campaigns with puppet show",
    "😂 Minister says gravity is a conspiracy in speech",
    "🎮 Bill introduced to replace taxes with online gaming rewards",
    "🍿 Free popcorn during election rallies announced",
    "🛑 New rule: Speeches longer than 10 mins get muted",
    "📜 Minister proposes compulsory karaoke in schools",
    "🏛 Parliament uses emojis instead of voting buttons",
    "📺 TV anchor challenges politician to rap battle",
    "📢 Campaign van plays lullabies instead of slogans",
    "😂 Politician says 'Wi-Fi is basic human right like water'",
    "🍦 Free ice cream day for voters who attend rallies",
    "🛵 Minister promises bike lanes for elephants",
    "🎭 Leader enters talent show to connect with youth",
    "🎤 Politician forgets speech and reads grocery list",
    "🪙 Coins replaced with memes as legal currency",
    "🏛 Parliament meeting ends with flash mob dance",
    "📜 Bill passed to allow naps in office for productivity",
    "📱 Politician launches campaign using dog filter on social media",
    "🎮 Leaders settle disputes in FIFA game tournament",
    "🚀 Minister says next rally will be on the moon",
    "🍕 Parliament orders pizza during night sessions",
    "🛶 Free boat rides promised for traffic jams",
    "🎤 Politician performs stand-up comedy at fundraiser",
    "🪑 All chairs in parliament replaced with bean bags",
    "😂 Minister introduces law making laughter tax-free",
    "📺 Election debates now include meme review section",
    "🏛 Politician promises underwater Wi-Fi",
    "🎯 All laws decided by spinning a wheel",
    "📢 Minister gives speech in rhyme for fun",
    "🎤 Politician sings national anthem in rap remix",
    "🍫 Free chocolates announced for budget day",
    "🚗 Leader promises free driving lessons for pets",
    "🎲 Lottery system introduced for minister selection",
    "📦 Minister receives Amazon parcel during live session",
    "🎭 Politician dresses as superhero to fight corruption",
    "🛑 Speeches over 20 mins replaced with TikTok video",
    "😂 Minister caught napping during his own speech",
    "🍟 Free fries for every voter on election day",
    "🎤 Debate moderator uses sound effects during arguments",
    "🎮 New bill makes gaming official sport of parliament",
    "📱 Politician promises 1GB data per sneeze",
    "🍩 National Donut Week declared for economy boost",
    "🏛 Parliament selfie contest announced for citizens",
    "🪑 Chairs in assembly replaced with bean bags",
    "📢 Politician campaigns from inside an ice cream truck",
    "🚲 Free bicycles for cows announced",
    "😂 Minister says exams should be optional forever",
    "🎭 Political ads now include dance routines",
    "🎤 Politician holds press conference in swimming pool",
    "🍕 Free pizza coupons distributed instead of manifestos",
    "📜 Law passed making memes legal documents",
    "🎯 Election winner decided by dart throw",
    "🚀 Minister promises first parliament meeting in space",
    "🛶 Boats added to metro system for fun rides",
    "📢 Campaign speech interrupted by ringtone ‘Baby Shark’",
    "🎤 Politician sings weather forecast during news",
    "📺 Assembly session streamed on Netflix as reality show",
    "😂 Minister says 'Netflix should be free for citizens'",
    "🍔 Free burgers announced in return for votes",
    "🎲 Parliament adopts 'Truth or Dare' decision-making",
    "🛵 Politician campaigns using food delivery bike",
    "📦 Minister receives gift hamper mid-speech",
    "🏛 Politician enters cooking reality show",
    "🎭 Bill passed for ‘Casual Friday’ in government offices",
    "📢 Politician gives speech with VR headset on",
    "🍫 Minister launches chocolate-based currency",
    "🪑 Chairs replaced with swings in parliament",
    "🎮 Assembly votes using gaming controllers",
    "🚀 Politician promises rocket rides for daily commute",
    "😂 Minister introduces law banning boring ties",
    "🎤 Politician freestyle raps during debate",
    "📺 Election coverage now with live reaction memes",
    "🍦 Free ice cream for every citizen on New Year",
    "🛶 River boat rallies introduced for eco-friendly campaigning",
    "🎯 Parliament decides budget using darts",
    "📱 Politician campaigns using Snapchat filters",
    "🎤 Press conference turns into karaoke night",
    "🍕 Politician promises pizza rain in next 5 years",
    "📜 New law makes clapping mandatory after every sentence",
    "😂 Minister says 'Selfies increase GDP' in speech",
    "🎭 Politician dresses as clown to entertain kids",
    "🎤 Debate includes singing competition",
    "📢 Campaign promises 5G for pets",
    "🍔 Parliament cafeteria serves only burgers for a week",
    "🎲 Policy decisions now based on rock-paper-scissors",
    "🚀 Election campaigns on Mars announced for future",
    "🛵 Minister rides scooter to office for publicity",
    "🍫 Politician throws chocolates instead of leaflets",
    "🎮 Parliament introduces gaming break in sessions",
    "📦 Free delivery promised for all taxes paid",
    "🎤 Minister forgets mic on, starts humming lullaby",
  ],
  tech: [
    "🏛 Politician accidentally joins dance reality show instead of debate",
    "📜 New law bans boring speeches, forces all to rhyme",
    "🤝 Rival leaders caught playing video games during summit",
    "📢 Parliament introduces karaoke Fridays for better attendance",
    "🏛 Politician forgets mic on, sings bathroom song during live session",
    "💼 Minister announces free Wi-Fi on Mars by 2050",
    "😂 President declares National Joke Day to boost happiness index",
    "🪑 Debate turns into musical chairs competition",
    "🚀 Politician promises moonlight dinner for all voters",
    "📺 Government launches reality show 'Who Wants to Be a Minister?'",
    "🍕 Law passed: Free pizza for every tax payer",
    "🎭 Politician spotted acting in street play to impress voters",
    "📜 Bill introduced to make naps mandatory at work",
    "📦 Parliament orders everything on Amazon Prime",
    "🏛 Politician campaigns using TikTok dance challenge",
    "🎤 Leader raps entire manifesto in campaign rally",
    "😂 Minister caught laughing at own meme in assembly",
    "🚗 Politician promises flying auto-rickshaws in next 2 years",
    "🍩 New rule: Donuts must be served in every cabinet meeting",
    "📺 TV debate turns into stand-up comedy night",
    "🎯 Politician starts free dart games to decide policies",
    "📢 Public speech interrupted by parrot repeating 'Vote for snacks!'",
    "🛒 Government plans 'Buy 1 Get 1' on petrol",
    "😂 Minister says AI should also pay taxes",
    "🎡 Politician organizes roller coaster rally for thrill-seeking voters",
    "🧢 Leader wears cap saying 'Make Tea Free Again'",
    "📜 Bill passed to make Mondays optional",
    "🛵 Politician promises scooters for dogs if elected",
    "📷 Selfie tax introduced for influencers",
    "🎲 New rule: Budget decided by rolling dice",
    "🍔 Free burgers announced during parliament adjournment",
    "🏛 Politician livestreams assembly meeting on Instagram",
    "🛶 Minister promises Venice-style boats in city traffic",
    "🎤 Debate moderator uses auto-tune by mistake",
    "📢 Politician campaigns with puppet show",
    "😂 Minister says gravity is a conspiracy in speech",
    "🎮 Bill introduced to replace taxes with online gaming rewards",
    "🍿 Free popcorn during election rallies announced",
    "🛑 New rule: Speeches longer than 10 mins get muted",
    "📜 Minister proposes compulsory karaoke in schools",
    "🏛 Parliament uses emojis instead of voting buttons",
    "📺 TV anchor challenges politician to rap battle",
    "📢 Campaign van plays lullabies instead of slogans",
    "😂 Politician says 'Wi-Fi is basic human right like water'",
    "🍦 Free ice cream day for voters who attend rallies",
    "🛵 Minister promises bike lanes for elephants",
    "🎭 Leader enters talent show to connect with youth",
    "🎤 Politician forgets speech and reads grocery list",
    "🪙 Coins replaced with memes as legal currency",
    "🏛 Parliament meeting ends with flash mob dance",
    "📜 Bill passed to allow naps in office for productivity",
    "📱 Politician launches campaign using dog filter on social media",
    "🎮 Leaders settle disputes in FIFA game tournament",
    "🚀 Minister says next rally will be on the moon",
    "🍕 Parliament orders pizza during night sessions",
    "🛶 Free boat rides promised for traffic jams",
    "🎤 Politician performs stand-up comedy at fundraiser",
    "🪑 All chairs in parliament replaced with bean bags",
    "😂 Minister introduces law making laughter tax-free",
    "📺 Election debates now include meme review section",
    "🏛 Politician promises underwater Wi-Fi",
    "🎯 All laws decided by spinning a wheel",
    "📢 Minister gives speech in rhyme for fun",
    "🎤 Politician sings national anthem in rap remix",
    "🍫 Free chocolates announced for budget day",
    "🚗 Leader promises free driving lessons for pets",
    "🎲 Lottery system introduced for minister selection",
    "📦 Minister receives Amazon parcel during live session",
    "🎭 Politician dresses as superhero to fight corruption",
    "🛑 Speeches over 20 mins replaced with TikTok video",
    "😂 Minister caught napping during his own speech",
    "🍟 Free fries for every voter on election day",
    "🎤 Debate moderator uses sound effects during arguments",
    "🎮 New bill makes gaming official sport of parliament",
    "📱 Politician promises 1GB data per sneeze",
    "🍩 National Donut Week declared for economy boost",
    "🏛 Parliament selfie contest announced for citizens",
    "🪑 Chairs in assembly replaced with bean bags",
    "📢 Politician campaigns from inside an ice cream truck",
    "🚲 Free bicycles for cows announced",
    "😂 Minister says exams should be optional forever",
    "🎭 Political ads now include dance routines",
    "🎤 Politician holds press conference in swimming pool",
    "🍕 Free pizza coupons distributed instead of manifestos",
    "📜 Law passed making memes legal documents",
    "🎯 Election winner decided by dart throw",
    "🚀 Minister promises first parliament meeting in space",
    "🛶 Boats added to metro system for fun rides",
    "📢 Campaign speech interrupted by ringtone ‘Baby Shark’",
    "🎤 Politician sings weather forecast during news",
    "📺 Assembly session streamed on Netflix as reality show",
    "😂 Minister says 'Netflix should be free for citizens'",
    "🍔 Free burgers announced in return for votes",
    "🎲 Parliament adopts 'Truth or Dare' decision-making",
    "🛵 Politician campaigns using food delivery bike",
    "📦 Minister receives gift hamper mid-speech",
    "🏛 Politician enters cooking reality show",
    "🎭 Bill passed for ‘Casual Friday’ in government offices",
    "📢 Politician gives speech with VR headset on",
    "🍫 Minister launches chocolate-based currency",
    "🪑 Chairs replaced with swings in parliament",
    "🎮 Assembly votes using gaming controllers",
    "🚀 Politician promises rocket rides for daily commute",
    "😂 Minister introduces law banning boring ties",
    "🎤 Politician freestyle raps during debate",
    "📺 Election coverage now with live reaction memes",
    "🍦 Free ice cream for every citizen on New Year",
    "🛶 River boat rallies introduced for eco-friendly campaigning",
    "🎯 Parliament decides budget using darts",
    "📱 Politician campaigns using Snapchat filters",
    "🎤 Press conference turns into karaoke night",
    "🍕 Politician promises pizza rain in next 5 years",
    "📜 New law makes clapping mandatory after every sentence",
    "😂 Minister says 'Selfies increase GDP' in speech",
    "🎭 Politician dresses as clown to entertain kids",
    "🎤 Debate includes singing competition",
    "📢 Campaign promises 5G for pets",
    "🍔 Parliament cafeteria serves only burgers for a week",
    "🎲 Policy decisions now based on rock-paper-scissors",
    "🚀 Election campaigns on Mars announced for future",
    "🛵 Minister rides scooter to office for publicity",
    "🍫 Politician throws chocolates instead of leaflets",
    "🎮 Parliament introduces gaming break in sessions",
    "📦 Free delivery promised for all taxes paid",
    "🎤 Minister forgets mic on, starts humming lullaby",
  ],
  entertainment: [
    "🎬 Director accidentally films his lunch, wins an award",
    "🍿 Movie theater now sells popcorn for the price of a car",
    "😂 Comedian laughs at own joke for 3 hours straight",
    "🎭 Actor forgets lines, starts singing grocery list",
    "🎤 Singer autotunes sneeze, tops the charts",
    "📺 Reality show contestant wins by taking the longest nap",
    "🎥 Movie titled ‘Untitled’ breaks box office record",
    "🕺 Dance competition winner was actually sleepwalking",
    "🎮 Movie adapted into a game, now being adapted back to movie",
    "🐍 Horror film uses real snake as cameraman",
    "🎸 Band names album after their Wi-Fi password",
    "📱 Influencer films 24-hour silence challenge, accidentally speaks at 23:59",
    "🎤 Singer performs with mic off, fans still cheer",
    "🍔 Cooking show judges raw onion salad as ‘modern art’",
    "🎬 Movie villain apologizes mid-fight for being rude",
    "😂 Stand-up comedian trips on stage, calls it part of the act",
    "🎭 Play pauses for 2 hours because actor lost shoe",
    "🎥 Director films entire movie upside down ‘for perspective’",
    "🎤 Pop star releases song with just breathing sounds",
    "📺 TV show ends on a cliffhanger—literally, actors hanging from cliff",
    "🍿 Movie about popcorn sells popcorn as merchandise",
    "🎮 Actor plays video game in movie, beats his own film’s villain",
    "🎬 Sequel announced before the first movie is even written",
    "🎤 Singer releases new single called ‘404 Not Found’",
    "🎭 Actor thanks his mirror in award speech",
    "😂 Comedian charges audience for laughing too hard",
    "🎥 Camera guy accidentally becomes main character",
    "🍔 Cooking show finale burns the entire kitchen",
    "🎤 Singer forgets lyrics, fans sing for her",
    "📱 Influencer goes viral for teaching how to blink",
    "🎬 Actor plays a tree and wins Best Actor award",
    "🍿 Popcorn brand sponsors thriller movie titled ‘Butter Fingers’",
    "🎮 Game movie cast gets stuck in actual game console",
    "🎭 Theater show becomes karaoke night after power cut",
    "🎥 Director accidentally casts his Uber driver as hero",
    "🎤 Song chorus only says ‘hmm’ for 3 minutes",
    "😂 Comedian uses audience’s phone for stand-up notes",
    "📺 Reality show contestants escape to avoid drama",
    "🍔 Chef uses glue instead of sauce on cooking show",
    "🎬 Zombie film actors accidentally scare real pedestrians",
    "🎮 Esports gamer wins acting award for crying in cutscene",
    "🎤 Pop star names album ‘Battery Low’",
    "🎭 Actor refuses to die in film, negotiates new script mid-scene",
    "🎥 Cameraman photobombs every movie scene intentionally",
    "🍿 Cinema charges extra for seats with ‘better air’",
    "😂 Comedian forgets punchline, audience laughs harder",
    "🎤 Music video filmed entirely in a moving elevator",
    "📱 Influencer starts challenge: ‘Breathe for 24 hours’",
    "🎬 Villain becomes hero because he says ‘sorry’",
    "🎭 Audience claps before play even starts",
    "🎥 Director films 10-hour nap documentary, wins an Oscar",
    "🍔 Chef makes invisible dish, judges call it ‘artistic’",
    "🎤 Singer autotunes pet’s bark into chartbuster",
    "😂 Stand-up show ends early because mic goes missing",
    "📺 TV host interviews wrong guest for entire episode",
    "🎮 Actor wins award for role in loading screen",
    "🎬 Trailer reveals entire movie including twist ending",
    "🎭 Actor eats prop food and gets real food poisoning",
    "🎤 Singer’s concert interrupted by her own ringtone",
    "🍿 Cinema sells popcorn with inspirational quotes inside",
    "📱 Influencer promotes toothpaste as face cream",
    "🎥 Film shot with front camera by mistake",
    "😂 Comedian performs for pets after humans leave",
    "🎤 Singer whispers entire song, fans call it ASMR",
    "🎭 Stage collapses, becomes modern art installation",
    "🎬 Movie script written in emojis only",
    "🍔 Cooking show adds a round for best food selfie",
    "📺 Drama series replaced by reality show mid-episode",
    "🎥 Actor falls asleep during emotional climax scene",
    "🎤 Pop star forgets she’s live and eats noodles on stage",
    "😂 Comedian uses silent mic, claims it’s a social experiment",
    "🍿 Movie about popcorn becomes a horror series",
    "🎬 Director shoots movie without actors using only shadows",
    "📱 Influencer livestreams nap, gains 1M followers",
    "🎭 Actor exits play mid-scene to get pizza",
    "🎤 Music video features random pigeons as backup dancers",
    "🎥 Cameraman does parkour while filming action scene",
    "🍔 Chef serves burnt dish as ‘Smoky Surprise’",
    "📺 News anchor accidentally joins reality show cast",
    "😂 Comedian roasts himself for 2 hours straight",
    "🎬 Hero and villain exchange Instagram handles mid-fight",
    "🎭 Play turns into stand-up after script is lost",
    "🎤 Singer forgets lyrics, sings menu instead",
    "🍿 Popcorn machine stars in new Netflix series",
    "🎮 Movie’s CGI monster becomes meme star",
    "📱 Influencer teaches dogs to use TikTok",
    "🎥 Movie uses real audience reactions as sound effects",
    "🎬 Director shoots movie entirely in a bathroom",
    "🍔 Chef creates sandwich so tall it gets its own zip code",
    "🎤 Music video has more product ads than music",
    "😂 Comedian wears clown wig by mistake, becomes trend",
    "📺 Reality show host accidentally wins his own show",
    "🎭 Actor plays 15 roles because no one else showed up",
    "🎥 Film uses random stock videos for climax",
    "🎬 Romantic movie ends with actors friend-zoning each other",
    "🎤 Singer starts yodeling in rap concert",
    "🍿 Movie theater charges for extra laughter",
    "📱 Influencer launches app to measure how funny you are",
    "🎮 Game-themed movie pauses for actual gaming session",
    "🎥 Director uses GoPro strapped to cat for filming",
    "😂 Comedian heckled by his own mom",
    "🎭 Audience gets stuck on stage after intermission",
    "🎤 Pop star names song ‘Wi-Fi Connection Lost’",
    "🍔 Cooking show replaces judges with parrots",
    "📺 Drama actor starts giving live cricket commentary",
    "🎬 Villain forgets to act evil and apologizes",
    "🎥 Cameraman becomes viral meme during movie release",
    "🎤 Singer dedicates love song to her laptop",
    "🍿 Cinema starts serving popcorn soup",
    "📱 Influencer live-streams staring contest with a wall",
    "🎭 Stage play converts into puppet show mid-performance",
    "🎥 Entire movie filmed during a power outage",
    "🎤 Pop band names album ‘Are We There Yet?’",
    "😂 Comedian laughs so hard he forgets his own jokes",
    "🎬 Hero carries script throughout film ‘for realism’",
    "🍔 Chef uses glitter as seasoning, calls it fancy",
    "📺 Reality show includes round of ‘Find Your Phone’",
    "🎥 Horror movie jump scare accidentally filmed in romantic scene",
    "🎤 Singer loses voice, concert becomes karaoke",
    "🍿 Popcorn machine goes on strike during premiere",
  ],
  health: [
    "🥗 Salad declared official breakfast, lunch & dinner by influencers",
    "🏃‍♂️ Guy runs marathon by mistake looking for Wi-Fi",
    "🍎 Apple named healthiest fruit, company stocks rise",
    "😂 Doctor prescribes Netflix for stress relief",
    "💤 New yoga trend: Sleeping in downward dog position",
    "🥦 Broccoli now comes in chocolate flavor for picky eaters",
    "🏋️‍♀️ Gym introduces ‘Lift Remote Control’ exercise",
    "🧘 Meditation retreat banned for too much talking",
    "🚶‍♂️ Walking backwards now called ‘Retro Fitness’",
    "🍔 Fast food chain introduces ‘Healthy Burger’ with one lettuce leaf",
    "💊 Doctor gives vitamin pills shaped like emojis",
    "😂 Fitness coach caught eating cake during live session",
    "🥗 Salad selfies become new fitness trend",
    "🚴 Man cycles to gym, leaves after realizing that was workout",
    "🏃‍♀️ Jogging in slow motion declared calming therapy",
    "🍫 Chocolate now marketed as ‘mental health booster’",
    "🛌 Sleeping 12 hours now called ‘Extreme Rest Training’",
    "🥦 Broccoli named ‘Food of the Year’ by fashion magazine",
    "💧 Water now being sold as luxury drink with fancy labels",
    "😂 Doctor diagnoses cough as ‘Netflix Season Binge Syndrome’",
    "🏋️ Gym launches subscription for ‘thinking about exercise’",
    "🍕 Pizza now counts as salad because of tomato sauce",
    "🧘 Yoga instructors start classes with TikTok dances",
    "🍎 Apple launch event mistaken for fruit health seminar",
    "🥗 Salad company offers free gym membership with 10 salads",
    "🚶 Walkathons now allow scooters for ‘motivation’",
    "💊 Doctor prescribes Wi-Fi for better mood",
    "😂 Patient claims laughter cured back pain, becomes comedian",
    "🥦 Green smoothie tastes like grass, chef calls it authentic",
    "🏃 Fitness tracker counts dreams as steps",
    "🛌 Bedtime stories added to fitness app as ‘mental cardio’",
    "🍔 Healthy burger includes free fries for balance",
    "💧 Water bottle now counts sips like a social media counter",
    "🍫 Dark chocolate promoted as vitamin supplement",
    "😂 Doctor recommends memes for heart health",
    "🏋️ Gym introduces nap corner for exhausted lifters",
    "🥗 Salad company creates hologram vegetables for virtual dieters",
    "🚴 Cycling trend: Use office chair wheels for home workout",
    "🧘 Meditation now done with headphones blasting EDM",
    "🍎 Apple juice renamed ‘Nature’s Energy Drink’",
    "💤 Sleeping mask now tracks dreams for fitness stats",
    "🥦 Broccoli launches motivational Instagram page",
    "😂 Doctor caught Googling symptoms during checkup",
    "🏃 Marathon now allows Netflix breaks mid-run",
    "🍕 Pizza crust labeled as ‘fitness fiber’",
    "💊 Energy pills shaped like smiley faces",
    "🍫 Chocolate bar now with ‘muscle-building’ marketing",
    "🛌 Sleeping contest declared Olympic sport",
    "🥗 Salad now delivered in pizza boxes to fool fast food lovers",
    "🚶 Walking challenge allows teleportation if tired",
    "🏋️ Dumbbells now sold in pastel colors for Instagram",
    "😂 Fitness app congratulates user for opening the app",
    "🍎 New fruit discovered: tastes like fries, looks like apple",
    "🥦 Broccoli smoothie now available in energy drink cans",
    "🧘 Yoga trend includes laughing for core strength",
    "🍔 Burger chain launches ‘detox burger’",
    "💧 Water now comes with caffeine for fitness freaks",
    "🏃‍♀️ Joggers start using roller skates for ‘speed yoga’",
    "🍫 Chocolate protein shake tastes like actual chocolate bar",
    "😂 Doctor prescribes ‘Take two TikToks and call me in the morning’",
    "🥗 Salad bar adds bacon for ‘protein boost’",
    "🛌 Fitness influencers promote ‘Sleep Gains’ challenge",
    "🏋️ Gym class teaches lifting spoons for dessert practice",
    "🍎 Fruit market launches subscription box for single grapes",
    "🥦 Broccoli pizza topping now a fitness must-have",
    "💊 Doctor warns against laughing too much—abs might hurt",
    "🚶 Man completes 10k steps while searching for remote",
    "🍕 Pizza called ‘round salad’ in new diet plan",
    "🧘 Meditation retreat now includes karaoke sessions",
    "😂 Fitness trainer loses weight yelling at clients",
    "🏃 Treadmill now with Netflix, Amazon, and snack holders",
    "🥗 Salad now comes with inspirational quotes",
    "🍫 Dark chocolate marketed as sleep medicine",
    "🛌 Sleep mask now streams calming memes",
    "🍎 Apple slices now sold like potato chips",
    "💧 Drinking water trend now includes fancy hashtags",
    "🥦 Broccoli festival includes smoothie wrestling",
    "🏋️ New gym rule: Take selfies every rep",
    "🚴 Fitness challenge: Ride stationary bike outdoors",
    "😂 Doctor prescribes vacation for chronic Zoom fatigue",
    "🍔 Burger made entirely of lettuce called ‘Nature’s Bite’",
    "🥗 Salad art exhibition opens in city",
    "🍫 Chocolate fountain now added in health expos",
    "🧘 Yoga class accidentally turns into nap marathon",
    "💊 Pill packs come with motivational compliments",
    "🏃‍♂️ Jogger wins race after taking wrong turn to donut shop",
    "🥦 Broccoli now promoted as luxury vegetable",
    "😂 Doctor writes prescription in emoji only",
    "🚶 Walk challenge includes virtual cheering crowd",
    "🍕 Pizza renamed ‘vegetable pie’ for healthy branding",
    "🍎 Fruit infused with glitter for party fitness",
    "💧 Water bottle now posts your hydration stats to Instagram",
    "🍫 Chocolate meditation sessions trending worldwide",
    "🛌 Sleep therapist accidentally falls asleep in session",
    "🏋️ Gym introduces penalty for skipping selfie posts",
    "🥗 Salad-based beauty masks become new spa trend",
    "🍔 Burger festival partners with fitness expo",
    "😂 Fitness instructor loses voice cheering on Zoom",
    "🍎 Apple-themed fashion show called ‘iRunway’",
    "🥦 Broccoli gains followers as meme star",
    "💊 Vitamin gummies shaped like favorite cartoon characters",
    "🚶 Walking app introduces leaderboard for slowest walkers",
    "🍫 Chocolate milk now marketed as recovery drink",
    "🧘 Yoga mat doubles as picnic blanket",
    "🍕 Pizza party called ‘Carb Loading Exercise’",
    "💧 Fancy water bottle costs more than gym membership",
    "😂 Doctor calls memes ‘mental multivitamins’",
    "🏋️ Gym offers treadmill-to-desk conversion kits",
    "🥗 Salad dressings now include glitter sprinkles",
    "🍔 Burger chain introduces kale milkshake",
    "🛌 Sleep podcast includes surprise loud noises for fun",
    "🥦 Broccoli phone cases trending among fitness geeks",
    "🍎 Fruit market starts selling ‘limited edition bananas’",
    "🏃 Virtual marathon allows participants to watch movies while running",
    "🍫 Chocolate-flavored toothpaste becomes new health trend",
    "😂 Fitness trainer loses weight by laughing at clients",
    "🧘 Yoga session ends with spontaneous dance party",
    "💊 Multivitamins now include daily jokes",
    "🚶 Walking group starts flash mobs during breaks",
    "🥗 Salad vending machines installed at gyms",
    "🍔 Fast food restaurant adds ‘meditation fries’ to menu",
  ],
};

// Typing animation
function typeText(element, text, speed = 50) {
  element.textContent = "";
  let i = 0;
  function typing() {
    if (i < text.length) {
      element.textContent += text.charAt(i);
      i++;
      setTimeout(typing, speed);
    }
  }
  typing();
}

const dropdownSelected = document.getElementById("selectedCategory");
const dropdownList = document.getElementById("dropdownList");
let selectedValue = null;

// Toggle dropdown
dropdownSelected.addEventListener("click", () => {
  dropdownList.classList.toggle("show");
});

// Select an option
dropdownList.querySelectorAll("li").forEach((item) => {
  item.addEventListener("click", () => {
    selectedValue = item.getAttribute("data-value");
    dropdownSelected.textContent = item.textContent;
    dropdownList.classList.remove("show");
  });
});

// Generate news
document.getElementById("generate").addEventListener("click", () => {
  if (!selectedValue) {
    alert("Please select a category first!");
    return;
  }
  const headlines = newsData[selectedValue];
  const randomHeadline =
    headlines[Math.floor(Math.random() * headlines.length)];
  const output = document.getElementById("output");
  typeText(output, randomHeadline, 40);
});

// Dark mode toggle
const darkModeToggle = document.getElementById("darkModeToggle");
darkModeToggle.addEventListener("click", () => {
  document.body.classList.toggle("dark-mode");
});
